/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo4.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import universidadgrupo4.control.*;
import universidadgrupo4.modelo.*;

/**
 *
 * @author kevin
 */
public class ViewInscripciones extends javax.swing.JInternalFrame {
    AlumnoData ad;
    MateriaData md;
    CursadaData cd;
    private DefaultTableModel tabla;
    
    /**
     * Creates new form ViewInscripciones
     */
    public ViewInscripciones(AlumnoData ad, MateriaData md, CursadaData cd) {
        initComponents();
        this.ad = ad;
        this.md = md;
        this.cd = cd;
        cargarAlumnos(jcbAlumno);
        cargarAlumnos(jcbAlumno1);
        cargarAlumnos(jcbAlumno2);
        jtNota2.setEditable(false);
        tabla = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        armarCabecera();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbAlumno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbMateria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtNota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbAlumno1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcbMateria1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtNota1 = new javax.swing.JTextField();
        jbActualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbAlumno2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcbMateria2 = new javax.swing.JComboBox<>();
        jbBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableDatos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jtNota2 = new javax.swing.JTextField();

        jcbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("INSCRIPCIONES");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("ALUMNO:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("MATERIA:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("NOTA:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("ACTUALIZAR");

        jbGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(51, 153, 255));
        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("ALUMNO:");

        jcbAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumno1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("MATERIA:");

        jcbMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateria1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setText("NOTA:");

        jbActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(51, 153, 255));
        jbActualizar.setText("ACTUALIZAR");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("ALUMNO:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setText("BORRAR CURSADA");

        jcbAlumno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumno2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setText("MATERIA:");

        jcbMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateria2ActionPerformed(evt);
            }
        });

        jbBorrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbBorrar.setForeground(new java.awt.Color(51, 153, 255));
        jbBorrar.setText("BORRAR");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jtableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDCURSADA", "IDALUMNO", "IDMATERIA", "NOTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableDatos);
        if (jtableDatos.getColumnModel().getColumnCount() > 0) {
            jtableDatos.getColumnModel().getColumn(0).setResizable(false);
            jtableDatos.getColumnModel().getColumn(1).setResizable(false);
            jtableDatos.getColumnModel().getColumn(2).setResizable(false);
            jtableDatos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setText("NOTA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbBorrar)
                                            .addComponent(jbGuardar)
                                            .addComponent(jbActualizar)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jcbAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel10)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGuardar))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcbAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbActualizar))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jcbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBorrar)
                    .addComponent(jLabel12)
                    .addComponent(jtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnoActionPerformed
        // TODO add your handling code here:
        Alumno alumno = (Alumno)jcbAlumno.getSelectedItem();
        jcbMateria.removeAllItems();
        cargarMateriasNoCursadas(alumno.getIdAlumno());
    }//GEN-LAST:event_jcbAlumnoActionPerformed

    private void jcbAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumno1ActionPerformed
        // TODO add your handling code here:
        Alumno alumno = (Alumno)jcbAlumno1.getSelectedItem();
        jcbMateria1.removeAllItems();
        for(Materia a:cd.traerMateriasCursaAlumno(alumno.getIdAlumno())){
            jcbMateria1.addItem(a);
        }
    }//GEN-LAST:event_jcbAlumno1ActionPerformed

    private void jcbAlumno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumno2ActionPerformed
        // TODO add your handling code here:
        Alumno alumno = (Alumno)jcbAlumno2.getSelectedItem();
        jcbMateria2.removeAllItems();
        for(Materia a:cd.traerMateriasCursaAlumno(alumno.getIdAlumno())){
            jcbMateria2.addItem(a);
        }
    }//GEN-LAST:event_jcbAlumno2ActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        int id = ((Alumno)jcbAlumno.getSelectedItem()).getIdAlumno();
        int idM = ((Materia)jcbMateria.getSelectedItem()).getIdMateria();
        double nota = Double.parseDouble(jtNota.getText());
        Cursada cursada = new Cursada(id, idM, nota);
        cd.guardarCursada(cursada);
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        int id = ((Alumno)jcbAlumno1.getSelectedItem()).getIdAlumno();
        int idM = ((Materia)jcbMateria1.getSelectedItem()).getIdMateria();
        double nota = Double.parseDouble(jtNota1.getText());
        
        cd.actualizarNotaCursada(id, idM, nota);
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jcbMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateria1ActionPerformed
        // TODO add your handling code here:
        int id = ((Alumno)jcbAlumno1.getSelectedItem()).getIdAlumno();
        int idM = ((Materia)jcbMateria1.getSelectedItem()).getIdMateria();
        
        jtNota1.setText(String.valueOf(cd.obtNotaEsp(id, idM)));
    }//GEN-LAST:event_jcbMateria1ActionPerformed

    private void jcbMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateria2ActionPerformed
        // TODO add your handling code here:
        int id = ((Alumno)jcbAlumno2.getSelectedItem()).getIdAlumno();
        int idM = ((Materia)jcbMateria2.getSelectedItem()).getIdMateria();
        
        jtNota2.setText(String.valueOf(cd.obtNotaEsp(id, idM)));
    }//GEN-LAST:event_jcbMateria2ActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        int id = ((Alumno)jcbAlumno2.getSelectedItem()).getIdAlumno();
        int idM = ((Materia)jcbMateria2.getSelectedItem()).getIdMateria();
        
        cd.borrarCursadaDeUnaMateriaDeUnAlumno(id, idM);
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void cargarAlumnos(JComboBox e){
        for(Alumno a: ad.traerAlumnos()){
            e.addItem(a);
        }
    }
    
    private void cargarMateriasNoCursadas(int id){
        List<Materia> materias = cd.traerMateriasNoCursaAlumno(id);
        for(Materia m:materias){
            jcbMateria.addItem(m);
        }
    }
    
    private void armarCabecera(){
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("IDCURSADA");
        columnas.add("IDALUMNO");
        columnas.add("IDMATERIA");
        columnas.add("NOTA");
        for(Object it:columnas){
            tabla.addColumn(it);
        }
        jtableDatos.setModel(tabla);
    }
    
    private void llenarTabla(){
        for(Cursada a:cd.obtenerCursadas()){
            tabla.addRow(new Object[]{a.getId_cursada(), a.getIdAlumno(), a.getIdMateria(), a.getNota()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JComboBox<Alumno> jcbAlumno;
    private javax.swing.JComboBox<Alumno> jcbAlumno1;
    private javax.swing.JComboBox<Alumno> jcbAlumno2;
    private javax.swing.JComboBox<Materia> jcbMateria;
    private javax.swing.JComboBox<Materia> jcbMateria1;
    private javax.swing.JComboBox<Materia> jcbMateria2;
    private javax.swing.JTextField jtNota;
    private javax.swing.JTextField jtNota1;
    private javax.swing.JTextField jtNota2;
    private javax.swing.JTable jtableDatos;
    // End of variables declaration//GEN-END:variables
}
